services:
  app:
    build:
      context: .
    environment:
      OLLAMA_HOST: "http://ollama:11434"

  ollama:
    image: ollama/ollama:0.2.6
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: { }